### PR TITLE
Update 2024-04-18-wg-agenda.md

### PR DESCRIPTION
**Pull request by inexorabletash**
Remove resolved bugs / merged PRs

There's a linked query for reviewing recently merged PRs

### CODE REVIEW

**Comment by inexorabletash** [comment]
FYI @anssiko

**Comment by inexorabletash** [comment]
FYI - via https://9-volt.github.io/bug-life/?repo=webmachinelearning/webnn - graph off issues (w/ labels) over time from 2018 to today. Notice the change in slope we've managed to achieve recently!

image

There's one new PR in discussion:

* webmachinelearning/webnn/pull/643
  *  ... which is a preamble to tackling webmachinelearning/webnn/issues/283

Other bugs worth potentially discussing, which seem like we could get consensus on:

* webmachinelearning/webnn/issues/391 
* webmachinelearning/webnn/issues/629

And in the interests of time, maybe don't bother bringing these up:

* webmachinelearning/webnn/issues/572 - no change from last time
* webmachinelearning/webnn/issues/571 - dependent on webmachinelearning/webnn#492

**Comment by inexorabletash** [comment]
We could also discuss 

- webmachinelearning/webnn/issues/625
   - webmachinelearning/webnn/pull/644 (proposed fix) bakes in a "lowest common denominator" limitation. Are we okay with that?

**Comment by anssiko** [comment]
Thanks @inexorabletash, I wasn’t expecting this much progress in a few days! 🚀

The open issue downward trend is encouraging and made possible by @inexorabletash @fdwr @huningxin and all others’ diligent efforts, supported by active implementation work.

Time allowing, we’ll look at the fresh new PRs and additional issues proposed.

My expectation is we’ll use adequate time to summarize the recent changes on our call. We can spend a bit more than usual on that this time.

(I need to consider changing ”any” to ”many” in this disclaimer I put in the agenda 😀: ”If any are addressed prior to the meeting, we'll debrief the group on the changes to keep everyone up to date with significant developments.”)

**Pull request merged**
